export const TAX_TYPES = [
  { type: "eu_vat", name: "EU VAT number" },
  { type: "gb_vat", name: "United Kingdom VAT number" },
  { type: "us_ein", name: "United States EIN" },
  { type: "au_abn", name: "Australian Business Number (AU ABN)" },
  { type: "au_arn", name: "Australian Taxation Office Reference Number" },
  { type: "br_cnpj", name: "Brazilian CNPJ number" },
  { type: "br_cpf", name: "Brazilian CPF number" },
  { type: "bg_uic", name: "Bulgaria Unified Identification Code" },
  { type: "ca_bn", name: "Canadian BN" },
  { type: "ca_gst_hst", name: "Canadian GST/HST number" },
  { type: "ca_pst_bc", name: "Canadian PST number (British Columbia)" },
  { type: "ca_pst_mb", name: "Canadian PST number (Manitoba)" },
  { type: "ca_pst_sk", name: "Canadian PST number (Saskatchewan)" },
  { type: "ca_qst", name: "Canadian QST number (Québec)" },
  { type: "cl_tin", name: "Chilean TIN" },
  { type: "eu_oss_vat", name: "European One Stop Shop VAT number for non-Union scheme" },
  { type: "ge_vat", name: "Georgian VAT" },
  { type: "hk_br", name: "Hong Kong BR number" },
  { type: "hu_tin", name: "Hungary tax number (adószám)" },
  { type: "is_vat", name: "Icelandic VAT" },
  { type: "in_gst", name: "Indian GST number" },
  { type: "id_npwp", name: "Indonesian NPWP number" },
  { type: "il_vat", name: "Israel VAT" },
  { type: "jp_cn", name: "Japanese Corporate Number (*Hōjin Bangō*)" },
  {
    type: "jp_rn",
    name: "Japanese Registered Foreign Businesses' Registration Number",
  },
  { type: "li_uid", name: "Liechtensteinian UID number" },
  { type: "my_frp", name: "Malaysian FRP number" },
  { type: "my_itn", name: "Malaysian ITN" },
  { type: "my_sst", name: "Malaysian SST number" },
  { type: "mx_rfc", name: "Mexican RFC number" },
  { type: "nz_gst", name: "New Zealand GST number" },
  { type: "no_vat", name: "Norwegian VAT number" },
  { type: "ru_inn", name: "Russian INN" },
  { type: "ru_kpp", name: "Russian KPP" },
  { type: "sa_vat", name: "Saudi Arabia VAT" },
  { type: "sg_gst", name: "Singaporean GST" },
  { type: "sg_uen", name: "Singaporean UEN" },
  { type: "si_tin", name: "Slovenia tax number (davčna številka)" },
  { type: "za_vat", name: "South African VAT number" },
  { type: "kr_brn", name: "Korean BRN" },
  { type: "es_cif", name: "Spanish CIF number" },
  { type: "ch_vat", name: "Switzerland VAT number" },
  { type: "tw_vat", name: "Taiwanese VAT" },
  { type: "th_vat", name: "Thai VAT" },
  { type: "ua_vat", name: "Ukrainian VAT" },
  { type: "ae_trn", name: "United Arab Emirates TRN" },
]
